module.exports = [
  {
    id: 1,
    item_name: "Savings",
    amount: "305.22",
    date: "2023-07-08",
    from: "Bank",
    category: "Savings",
  },
  {
    id: 2,
    item_name: "Groceries",
    amount: "-112.34",
    date: "2023-10-19",
    from: "Grocery Store",
    category: "Food",
  },
  {
    id: 3,
    item_name: "Rent",
    amount: "-950.00",
    date: "2023-05-23",
    from: "Landlord",
    category: "Bills",
  },
  {
    id: 4,
    item_name: "Income",
    amount: "1500.00",
    date: "2023-03-11",
    from: "Employer",
    category: "Income",
  },
  {
    id: 5,
    item_name: "Dining Out",
    amount: "-45.67",
    date: "2023-06-30",
    from: "Restaurant",
    category: "Food",
  },
  {
    id: 6,
    item_name: "Entertainment",
    amount: "-120.00",
    date: "2023-02-14",
    from: "Entertainment Venue",
    category: "Entertainment",
  },
  {
    id: 7,
    item_name: "Utilities",
    amount: "-75.32",
    date: "2023-01-29",
    from: "Utility Company",
    category: "Bills",
  },
  {
    id: 8,
    item_name: "Fish Food",
    amount: "-30.25",
    date: "2023-09-05",
    from: "Pet Store",
    category: "Pets",
  },
  {
    id: 9,
    item_name: "Income",
    amount: "1300.00",
    date: "2023-11-21",
    from: "Employer",
    category: "Income",
  },
  {
    id: 10,
    item_name: "Savings",
    amount: "500.00",
    date: "2023-04-17",
    from: "Bank",
    category: "Savings",
  },
  {
    id: 11,
    item_name: "Groceries",
    amount: "-80.45",
    date: "2023-03-07",
    from: "Grocery Store",
    category: "Food",
  },
  {
    id: 12,
    item_name: "Rent",
    amount: "-950.00",
    date: "2023-06-13",
    from: "Landlord",
    category: "Bills",
  },
  {
    id: 13,
    item_name: "Dining Out",
    amount: "-62.50",
    date: "2023-08-25",
    from: "Restaurant",
    category: "Food",
  },
  {
    id: 14,
    item_name: "Entertainment",
    amount: "-85.00",
    date: "2023-05-19",
    from: "Entertainment Venue",
    category: "Entertainment",
  },
  {
    id: 15,
    item_name: "Utilities",
    amount: "-90.50",
    date: "2023-07-15",
    from: "Utility Company",
    category: "Bills",
  },
  {
    id: 16,
    item_name: "Fish Food",
    amount: "-20.00",
    date: "2023-09-30",
    from: "Pet Store",
    category: "Pets",
  },
  {
    id: 17,
    item_name: "Income",
    amount: "1450.00",
    date: "2023-12-01",
    from: "Employer",
    category: "Income",
  },
  {
    id: 18,
    item_name: "Savings",
    amount: "600.00",
    date: "2023-01-23",
    from: "Bank",
    category: "Savings",
  },
  {
    id: 19,
    item_name: "Groceries",
    amount: "-95.75",
    date: "2023-11-12",
    from: "Grocery Store",
    category: "Food",
  },
  {
    id: 20,
    item_name: "Rent",
    amount: "-950.00",
    date: "2023-02-10",
    from: "Landlord",
    category: "Bills",
  },
];
